apiVersion: v1
stringData:
  username: clusteruser
  password: clusterpassword
kind: Secret
metadata:
  name: app-secret
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: fnd-db
spec:
  instances: 3

  bootstrap:
    initdb:
      database: ordersdb
      owner: clusteruser
      secret:
        name: app-secret

  storage:
    size: 1Gi