apiVersion: v1
kind: Service
metadata:
  name: fnd-task3
  namespace: default
spec:
  type: ClusterIP
  selector:
    tier: frontend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP