apiVersion: v1
kind: Secret
metadata:
  name: kcsecrets
  namespace: default
  labels:
    app.kubernetes.io/instance: gateway-kc
type: Opaque
data:
  kc-client-secret: Yk1kb01TSEpXckZtekRMYlI0d3Z5VTA3cDFESW56U0k=