apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: gateway-kc
spec:
  ingress:
    enabled: false
  instances: 1
  db:
    vendor: postgres
    host: kc-postgresql
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: kc-postgresql
      key: password
  http:
    httpEnabled: true
    httpPort: 8080
    httpsPort: 8443
    tlsSecret: keycloak-tls-secret
  hostname:
    hostname: test.keycloak.org
    #strict: false
  proxy:
    headers: xforwarded