apiVersion: v1
kind: Service
metadata:
  name: gateway-kc-service-loadbalancer
spec:
  selector:
    app: keycloak
    app.kubernetes.io/instance: gateway-kc
    app.kubernetes.io/managed-by: keycloak-operator
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      name: http
    - port: 8443
      targetPort: 8443
      nodePort: 30443
      name: https