spring.application.name=foodndeliv

# Base API path
spring.data.rest.base-path=/api

# PostgreSQL 
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_Name:ordersdb}
spring.datasource.username=${DB_USER:myadmin}
spring.datasource.password=${DB_PASSWORD}

# JPA 
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HikariCP settings
spring.datasource.hikari.minimum-idle=5           
spring.datasource.hikari.maximum-pool-size=20     
spring.datasource.hikari.idle-timeout=30000       
spring.datasource.hikari.max-lifetime=1800000     
spring.datasource.hikari.connection-timeout=30000 
spring.datasource.hikari.pool-name=MyHikariPool   

# OpenAPI 
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

#Actuator
management.endpoint.prometheus.enabled=true
management.endpoints.web.exposure.include=*

#otel
otel.resource.attributes.service.name=foodndeliv
otel.resource.attributes.service.namespace=example.org

#keycloak
keycloak.server-url=http://${IAM_HOST:my-keycloak}:${IAM_PORT:80}
keycloak.realm=master
keycloak.client-id=admin-cli
keycloak.client-secret=${IAM_CLIENT_SECRET}
keycloak.username=admin                  
keycloak.password=${IAM_PASSWORD}
keycloak.target-realm=fnd



